# Generated by Django 3.0.4 on 2020-05-11 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.BaseContent')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_status', models.IntegerField(choices=[(1, 'Open'), (2, 'In progress'), (3, 'verified'), (4, 'To verify'), (5, 'closed')], null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('project.basecontent',),
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.BaseContent')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('weightage', models.FloatField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.Activity')),
            ],
            bases=('project.basecontent',),
        ),
    ]
