# Generated by Django 3.0.4 on 2020-05-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWeightage',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.BaseContent')),
                ('weightage', models.FloatField()),
            ],
            bases=('project.basecontent',),
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='weightage',
        ),
    ]
