# Generated by Django 3.0.4 on 2020-05-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observationdate', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('lastupdate', models.CharField(max_length=30)),
                ('confirmed', models.FloatField(max_length=30)),
                ('death', models.FloatField(max_length=30)),
                ('recovered', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survived', models.IntegerField()),
                ('pclass', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.FloatField()),
                ('sibsp', models.FloatField()),
                ('parch', models.FloatField()),
                ('ticket', models.CharField(max_length=20)),
                ('fare', models.FloatField()),
                ('cabin', models.CharField(max_length=20)),
                ('embarked', models.CharField(max_length=20)),
            ],
        ),
    ]
