# Generated by Django 3.0.4 on 2020-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_api_app', '0002_covidjson_titanicjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='confirmed',
            field=models.FloatField(max_length=300),
        ),
        migrations.AlterField(
            model_name='covid',
            name='country',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='covid',
            name='death',
            field=models.FloatField(max_length=300),
        ),
        migrations.AlterField(
            model_name='covid',
            name='lastupdate',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='covid',
            name='observationdate',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='covid',
            name='recovered',
            field=models.FloatField(max_length=300),
        ),
        migrations.AlterField(
            model_name='covid',
            name='state',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='cabin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='embarked',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='sex',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='ticket',
            field=models.CharField(max_length=200),
        ),
    ]
