# Generated by Django 3.0.4 on 2020-05-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_api_app', '0003_auto_20200508_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidjson',
            old_name='data',
            new_name='data_json',
        ),
        migrations.RenameField(
            model_name='titanicjson',
            old_name='data',
            new_name='data_json',
        ),
    ]
